# Generated by Django 4.0.6 on 2022-07-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30, verbose_name='Street')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=20, verbose_name='Province')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('film_genre', models.CharField(max_length=20)),
                ('duration', models.DurationField()),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rental')),
            ],
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('music_genre', models.CharField(max_length=20)),
                ('track_list', models.TextField()),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rental')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('book_genre', models.CharField(max_length=20)),
                ('ISBN', models.CharField(max_length=13)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rental')),
            ],
        ),
    ]
