# Generated by Django 4.0.6 on 2022-07-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='country',
        ),
        migrations.AlterField(
            model_name='rental',
            name='province',
            field=models.CharField(choices=[('dolnośląskie', 'dolnośląskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('łódzkie', 'łódzkie'), ('małopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('śląskie', 'śląskie'), ('świętokrzyskie', 'świętokrzyskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=20),
        ),
    ]
