# Generated by Django 4.0.6 on 2022-07-12 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0002_remove_rental_country_alter_rental_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishing_house',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.CharField(choices=[('fantastyka', 'Fantastyka'), ('kryminał', 'Kryminał'), ('popularno-naukowe', 'Popularno-naukowe'), ('powieść historyczna', 'Powieść historyczna'), ('romans', 'Romans'), ('thriller', 'Thriller')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rental',
            name='province',
            field=models.CharField(choices=[('DSL', 'dolnośląskie'), ('KP', 'kujawsko-pomorskie'), ('LBL', 'lubelskie'), ('LBU', 'lubuskie'), ('LDZ', 'łódzkie'), ('MLP', 'małopolskie'), ('MAZ', 'mazowieckie'), ('OPO', 'opolskie'), ('PKR', 'podkarpackie'), ('PDL', 'podlaskie'), ('POM', 'pomorskie'), ('SL', 'śląskie'), ('SW', 'świętokrzyskie'), ('WM', 'warmińsko-mazurskie'), ('WLKP', 'wielkopolskie'), ('ZPM', 'zachodniopomorskie')], max_length=20, verbose_name='Province'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
